### ISSUE TITLE
What does the acronym "rwvpvf" stand for?

### ISSUE THREAD

**Issue by dirkgruending** [AndreWeiner/phd_openfoam#1]

**Comment by AndreWeiner** [comment]
_rwvpvf_ stands for _rotating wall velocity fvPatch vector field_. This naming is just a leftover from the [original boundary condition](https://www.openfoam.com/documentation/guides/latest/api/classFoam_1_1rotatingWallVelocityFvPatchVectorField.html) I used as a base.
