### ISSUE TITLE
Commenting

### ISSUE THREAD

**Issue by dirkgruending** [AndreWeiner/phd_openfoam#2]
bubbleSurfaceVelocitySimpleFvPatchVectorField.H:
Why do you need to compute the tangential component for the velocity? In a co-moving reference frame in the quasi-stationary state, the normal component of the velocity field should be (close to) zero anyway. 
Elaborate on the definition of normal_. What normal is this precisely?
What is the "normal" that I have to specify in the patchField dict? The normal of which plane?
Why are origin_, axis_, and normal_ required in general. Please add a comment.

bubbleSurfaceVelocitySimpleFvPatchVectorField.C:
Give a short description of what a torch::Tensor is as a comment.

**Comment by AndreWeiner** [comment]
> Why do you need to compute the tangential component for the velocity? In a co-moving reference frame in the quasi-stationary state, the normal component of the velocity field should be (close to) zero anyway.

The ML model returns the tangential component of the velocity vector for a given polar angle. The normal component of the velocity is indeed zero. The velocity vector at the boundary has the length returned by the ML model and points in the direction tangential to the surface. Tangential is here defined as the cross product between the _plane_ normal vector (see below) and the surface normal vector.

> Elaborate on the definition of normal_. What normal is this precisely?

normal_ is what I call plane normal vector. Imagine a Cartesian coordinate system x,y,z. In all the test cases in this repository, the wedge mesh extends in the x-y-plane and is symmetric with respect to z=0. So the plane normal would be the z-axis.

> Why are origin_, axis_, and normal_ required in general. Please add a comment.

origin and axis are not really necessary for the test cases in this repository. To compute the polar angle, the position vector of a face on the boundary must be given in a coordinate system that has its origin in the bubble's center of mass. If the origin of the mesh is not identical with the bubble's center of mass, or if the coordinate system is rotated, origin and axis are used to move or rotate the coordinate system.

> Give a short description of what a torch::Tensor is as a comment.

Automatically differentiable, efficient CPU and GPU enabled tensors. [source](https://pytorch.org/cppdocs/frontend.html)
