### ISSUE TITLE
Is there a specific reason why the "complex" boundary condition is not inheriting from the "simple" boundary condition?

### ISSUE THREAD

**Issue by dirkgruending** [AndreWeiner/phd_openfoam#4]
What additional feature is the "complex" version offering in comparison to the "simple" implementation?

**Comment by dirkgruending** [comment]
What additional feature is the "complex" version offering in comparison to the "simple" implementation?

**Comment by AndreWeiner** [comment]
The functionality of both boundary conditions could be merged into a single boundary condition with some logic or flags. The main reason for the current implementation is related to the timeline of implementation and the lack of time to put more thought into the design and refactoring, respectively.

The _simple_ version computes the tangential velocity component as a function of the polar angle. This boundary condition works only for star-shaped boundaries, with the star-point being the bubble's center of mass. The _complex_ implementation also works for non-star-shaped boundaries, e.g. dimpled ellipsoidal or skirted bubbles. The additional workflow for the latter case is:

1. based on the position vector, evaluate if the point is on the inner or on the outer contour
2. evaluate the corresponding velocity model; there is one model for the inner and one model for the outer contour

For more information, refer to section 6 in the [referenced thesis](https://tuprints.ulb.tu-darmstadt.de/cgi/users/home?screen=EPrint%3A%3AView&eprintid=11405).
